name: TestPyPI

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+[ab][0-9]*

env:
  TWINE_USERNAME: __token__
  TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
  TWINE_REPOSITORY_URL: 'https://test.pypi.org/legacy/'

jobs:
  build-and-publish:
    name: Build and publish to TestPyPI
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      CIBW_BUILD: 'cp38-* cp39-* cp310-*'
      CIBW_SKIP: '*-musllinux_*'
      CIBW_ARCHS_MACOS: "x86_64 arm64"
      CIBW_ARCHS_LINUX: "x86_64 aarch64"


    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
          channel-priority: true

      - name: Install cibuildwheel
        run: |
          conda install pip
          python --version
          pip --version
          python -m pip install cibuildwheel==2.3.0

      - name: Show conda installation info
        run: |
          conda info
          conda list

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse

      - name: Build source distribution
        if: matrix.os == 'ubuntu-latest'
        run: |
          python setup.py sdist --dist-dir wheelhouse

      - name: Upload distributions
        run: |
          pip install twine
          twine upload --skip-existing wheelhouse/*.whl
          twine upload --skip-existing wheelhouse/*.tar.gz

